#### Import the necessary packages

In [36]:
import numpy as np
import pandas as pd
from pyod.models.knn import KNN


from sklearn.preprocessing import MinMaxScaler

In [37]:
car_df = pd.read_csv('cars.csv')

In [38]:
car_df.head()

mpg  cyl   disp   hp    wt   acc  yr  origin                   car_name
0  18.0    8  307.0  130  3504  12.0  70       1  chevrolet chevelle malibu
1  15.0    8  350.0  165  3693  11.5  70       1          buick skylark 320
2  18.0    8  318.0  150  3436  11.0  70       1         plymouth satellite
3  16.0    8  304.0  150  3433  12.0  70       1              amc rebel sst
4  17.0    8  302.0  140  3449  10.5  70       1                ford torino

In [39]:
car_df.drop('car_name', axis=1, inplace=True)

In [40]:
car_df.head()

mpg  cyl   disp   hp    wt   acc  yr  origin
0  18.0    8  307.0  130  3504  12.0  70       1
1  15.0    8  350.0  165  3693  11.5  70       1
2  18.0    8  318.0  150  3436  11.0  70       1
3  16.0    8  304.0  150  3433  12.0  70       1
4  17.0    8  302.0  140  3449  10.5  70       1

In [41]:
car_df.drop(car_df[car_df['hp'] == '?'].index, axis=0, inplace=True)

In [42]:
print('The shape of the input data:',car_df.shape)

The shape of the input data: (392, 8)


In [43]:
#lets apply zscore to compress the data between zero and one
minmaxscaler = MinMaxScaler()

for i in car_df:
    car_df[i] = minmaxscaler.fit_transform(np.array(car_df[i]).reshape(-1,1))

In [44]:
car_df.head()

mpg  cyl      disp        hp        wt       acc   yr  origin
0  0.239362  1.0  0.617571  0.456522  0.536150  0.238095  0.0     0.0
1  0.159574  1.0  0.728682  0.646739  0.589736  0.208333  0.0     0.0
2  0.239362  1.0  0.645995  0.565217  0.516870  0.178571  0.0     0.0
3  0.186170  1.0  0.609819  0.565217  0.516019  0.238095  0.0     0.0
4  0.212766  1.0  0.604651  0.510870  0.520556  0.148810  0.0     0.0

In [45]:
knn = KNN()

In [46]:
knn.fit(car_df)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [53]:
knn.decision_function(car_df)[:14]

array([0.20860148, 0.17303535, 0.16138242, 0.16673789, 0.19570092,
       0.19514153, 0.25099795, 0.23025746, 0.23284013, 0.2282685 ,
       0.17421003, 0.22257054, 0.2282685 , 0.37810072])

In [48]:
predict_knn = knn.predict(car_df)

In [52]:
predict_knn[:14]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [54]:
knn = KNN(method='mean')

In [55]:
knn.fit(car_df)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='mean',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [56]:
knn.decision_function(car_df)[:14]

array([0.11397214, 0.1265675 , 0.09136155, 0.09707588, 0.09853965,
       0.12914156, 0.10514614, 0.10724059, 0.11652621, 0.16256746,
       0.12054983, 0.16103413, 0.1499939 , 0.29099461])

In [57]:
predict_knn = knn.predict(car_df)

In [58]:
predict_knn[:14]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])